{
    'name': "Aronia",
    'description': "ARONIA",
    'summary': "",
    'author': 'ARONIA',
    'category': 'base',
    'version': '1.0',
    'description': """
        This module introduces custom features for Aronia
    """,
    'author': 'ARONIA',
    'website': 'http://www.aronia.com',
    'category': '',
    'depends': ['base','product','queue_job','sale_management', 'stock', 'account'],
    'data': [
        'views/product_product_prestashop.xml',
        'views/view_product_prestashop_number.xml',
        'views/view_product_template_prestashop.xml',
        'views/order.xml',
        'views/number_max.xml',
        'views/generate_batch.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/fetch.xml',
        'data/cron_variante.xml',
        'data/update_stock.xml',
        'data/check_status_after_picking.xml',
        'data/create_sale_order.xml',
        'data/invoice.xml',
        'data/shipping_number.xml',
        'data/sync_status_to_prestashop.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
